{"uuid": "c13f1bab-ba60-4e47-8c5c-45db702ff446", "children": ["40f3f15b-be9d-4b4e-b638-0421c5e431a9"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=139.0.7258.155)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7e7f73d85+79397]\n\tGetHandleVerifier [0x0x7ff7e7f73de0+79488]\n\t(No symbol) [0x0x7ff7e7d1c0fa]\n\t(No symbol) [0x0x7ff7e7d08d60]\n\t(No symbol) [0x0x7ff7e7d0747c]\n\t(No symbol) [0x0x7ff7e7d07d2f]\n\t(No symbol) [0x0x7ff7e7d32fab]\n\t(No symbol) [0x0x7ff7e7d265d0]\n\t(No symbol) [0x0x7ff7e7d26472]\n\t(No symbol) [0x0x7ff7e7cf8242]\n\t(No symbol) [0x0x7ff7e7cf6233]\n\t(No symbol) [0x0x7ff7e7ddb581]\n\t(No symbol) [0x0x7ff7e7d9b19a]\n\t(No symbol) [0x0x7ff7e7dc3344]\n\t(No symbol) [0x0x7ff7e7d9af73]\n\t(No symbol) [0x0x7ff7e7d641b1]\n\t(No symbol) [0x0x7ff7e7d64f43]\n\tGetHandleVerifier [0x0x7ff7e823e1ed+3005069]\n\tGetHandleVerifier [0x0x7ff7e823831d+2980797]\n\tGetHandleVerifier [0x0x7ff7e8257e0d+3110573]\n\tGetHandleVerifier [0x0x7ff7e7f8d6de+184190]\n\tGetHandleVerifier [0x0x7ff7e7f9516f+215567]\n\tGetHandleVerifier [0x0x7ff7e7f7c974+115220]\n\tGetHandleVerifier [0x0x7ff7e7f7cb29+115657]\n\tGetHandleVerifier [0x0x7ff7e7f63268+11016]\n\tBaseThreadInitThunk [0x0x7ffa732fe8d7+23]\n\tRtlUserThreadStart [0x0x7ffa74a9c34c+44]\n\n", "trace": "  File \"C:\\python-3.8\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\python-3.8\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\python-3.8\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python-3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python-3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\GUVI\\Project\\Mini_Project2\\tests\\conftest.py\", line 106, in driver\n    driver.maximize_window()\n  File \"C:\\python-3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n  File \"C:\\python-3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python-3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1757106533506, "stop": 1757106537528}], "start": 1757106533506, "stop": 1757106550367}